/**
 * Database Produk List Gypsum & Aksesoris
 * Data katalog lengkap dengan spesifikasi, ukuran, dan harga
 */

const GYPSUM_PRODUCTS = [
  {
    id: "gp-01",
    code: "GP-101",
    name: "List Gypsum Minimalis Step 7cm",
    category: "minimalis",
    categoryLabel: "Minimalis & Modern",
    width: "7 cm",
    widthNumber: 7,
    length: "2.10 meter",
    lengthMeter: 2.1,
    price: 13500,
    priceBulk: 11000,
    minBulkQty: 50,
    rating: 4.9,
    sold: 1420,
    isPopular: true,
    isBestSeller: true,
    image: "assets/images/list-minimalis.jpg",
    description: "List profil gypsum minimalis corak bertingkat (step-profile). Sangat cocok untuk rumah tipe modern minimalis, apartemen, dan ruang kantor. Presisi sudut 90 derajat memudahkan pemotongan miter.",
    specs: [
      { label: "Bahan", value: "Tepung Casting A-Grade + Serat Roving Berkualitas" },
      { label: "Panjang Efektif", value: "2.10 Meter / Batang" },
      { label: "Lebar Muka", value: "7 cm" },
      { label: "Ketebalan", value: "12 - 14 mm (Kuat & Tidak Melengkung)" },
      { label: "Finishing", value: "Permukaan Halus, Siap Cat Dasar (Porous Free)" }
    ]
  },
  {
    id: "gp-02",
    code: "GP-102",
    name: "List Gypsum Minimalis Bertingkat 10cm",
    category: "minimalis",
    categoryLabel: "Minimalis & Modern",
    width: "10 cm",
    widthNumber: 10,
    length: "2.10 meter",
    lengthMeter: 2.1,
    price: 17500,
    priceBulk: 14500,
    minBulkQty: 50,
    rating: 5.0,
    sold: 2150,
    isPopular: true,
    isBestSeller: true,
    image: "assets/images/list-minimalis.jpg",
    description: "Model best seller terfavorit para kontraktor dan desainer interior. Profil garis tegas memberikan ilusi plafon tampak lebih tinggi dan rapi.",
    specs: [
      { label: "Bahan", value: "Gypsum Casting Roving High Density" },
      { label: "Panjang Efektif", value: "2.10 Meter / Batang" },
      { label: "Lebar Muka", value: "10 cm" },
      { label: "Ketebalan", value: "14 mm" },
      { label: "Karakteristik", value: "Tahan Retak, Presisi Tinggi" }
    ]
  },
  {
    id: "gp-03",
    code: "GP-103",
    name: "List Minimalis Garis Dobel 12cm",
    category: "minimalis",
    categoryLabel: "Minimalis & Modern",
    width: "12 cm",
    widthNumber: 12,
    length: "2.20 meter",
    lengthMeter: 2.2,
    price: 22000,
    priceBulk: 18500,
    minBulkQty: 40,
    rating: 4.8,
    sold: 890,
    isPopular: false,
    isBestSeller: false,
    image: "assets/images/list-minimalis.jpg",
    description: "Ukuran ideal untuk ruangan dengan ketinggian plafon 3 - 3.5 meter. Tampilan elegan tanpa terkesan berlebihan.",
    specs: [
      { label: "Bahan", value: "Gypsum Casting Super + 3 Lapis Serat Roving" },
      { label: "Panjang Efektif", value: "2.20 Meter / Batang" },
      { label: "Lebar Muka", value: "12 cm" },
      { label: "Ketebalan", value: "15 mm" },
      { label: "Pemasangan", value: "Menggunakan Perekat Kompon Khusus" }
    ]
  },
  {
    id: "gp-04",
    code: "GP-201",
    name: "List Profil Klasik Ukir Daun Acanthus 15cm",
    category: "klasik",
    categoryLabel: "Klasik & Mewah",
    width: "15 cm",
    widthNumber: 15,
    length: "2.10 meter",
    lengthMeter: 2.1,
    price: 32000,
    priceBulk: 27500,
    minBulkQty: 30,
    rating: 4.9,
    sold: 730,
    isPopular: true,
    isBestSeller: false,
    image: "assets/images/list-klasik.jpg",
    description: "Karya seni cetakan gypsum klasik bergaya Baroque Eropa. Ukiran relief daun Acanthus yang tajam, sangat mewah untuk ruang tamu, aula, dan rumah mewah bergaya klasik Amerika atau Mediterania.",
    specs: [
      { label: "Bahan", value: "Gypsum Casting Premium + Serat Roving Tebal" },
      { label: "Panjang Efektif", value: "2.10 Meter / Batang" },
      { label: "Lebar Muka", value: "15 cm" },
      { label: "Ketebalan", value: "18 mm" },
      { label: "Kelebihan", value: "Detail Ukiran Tajam & Tidak Mudah Gompal" }
    ]
  },
  {
    id: "gp-05",
    code: "GP-202",
    name: "List Cornice Klasik Royal Roman 18cm",
    category: "klasik",
    categoryLabel: "Klasik & Mewah",
    width: "18 cm",
    widthNumber: 18,
    length: "2.10 meter",
    lengthMeter: 2.1,
    price: 39500,
    priceBulk: 34000,
    minBulkQty: 30,
    rating: 5.0,
    sold: 520,
    isPopular: false,
    isBestSeller: false,
    image: "assets/images/list-klasik.jpg",
    description: "Ukuran jumbo untuk void tangga, ruang tamu berplafon tinggi (>3.8 meter), serta ballroom. Memberikan nuansa megah istana.",
    specs: [
      { label: "Bahan", value: "Casting Gypsum Padat + Sisipan Roving Ganda" },
      { label: "Panjang Efektif", value: "2.10 Meter / Batang" },
      { label: "Lebar Muka", value: "18 cm" },
      { label: "Ketebalan", value: "20 mm" },
      { label: "Berat Batang", value: "± 3.8 kg" }
    ]
  },
  {
    id: "gp-06",
    code: "GP-301",
    name: "Shadowline / Tali Air Drop Ceiling 3x3 cm",
    category: "shadowline",
    categoryLabel: "Shadowline & Tali Air",
    width: "3 x 3 cm",
    widthNumber: 3,
    length: "2.40 meter",
    lengthMeter: 2.4,
    price: 15000,
    priceBulk: 12500,
    minBulkQty: 50,
    rating: 4.9,
    sold: 3400,
    isPopular: true,
    isBestSeller: true,
    image: "assets/images/shadowline.jpg",
    description: "List profil pembentuk celah bayangan (shadowline / tali air) modern. Pilihan utama arsitek masa kini untuk tepian plafon tanpa list sudut konvensional, serta untuk cove drop ceiling lampu LED strip.",
    specs: [
      { label: "Bahan", value: "Gypsum Roving Presisi Ekstra Keras" },
      { label: "Panjang Efektif", value: "2.40 Meter / Batang" },
      { label: "Ukuran Celah", value: "3 cm x 3 cm" },
      { label: "Kelebihan", value: "Garis Lurus Sempurna, Mudah Dipasang Bersama Rangka Hollow" }
    ]
  },
  {
    id: "gp-07",
    code: "GP-302",
    name: "Shadowline Drop Celah Lebar 4x4 cm",
    category: "shadowline",
    categoryLabel: "Shadowline & Tali Air",
    width: "4 x 4 cm",
    widthNumber: 4,
    length: "2.40 meter",
    lengthMeter: 2.4,
    price: 18000,
    priceBulk: 15000,
    minBulkQty: 50,
    rating: 4.8,
    sold: 1100,
    isPopular: false,
    isBestSeller: false,
    image: "assets/images/shadowline.jpg",
    description: "Solusi sempurna untuk drop ceiling dengan housing lampu tersembunyi (hidden LED indirect light). Ruang celah leluasa untuk sirkulasi panas lampu.",
    specs: [
      { label: "Bahan", value: "High Grade Gypsum Plaster" },
      { label: "Panjang Efektif", value: "2.40 Meter / Batang" },
      { label: "Dimensi Celah", value: "4 cm x 4 cm" },
      { label: "Kelebihan", value: "Hasil Siku Rapi Tanpa Gelombang" }
    ]
  },
  {
    id: "gp-08",
    code: "GP-401",
    name: "List Wall Moulding Pigura Dinding 4cm",
    category: "wall-moulding",
    categoryLabel: "Wall Moulding Dinding",
    width: "4 cm",
    widthNumber: 4,
    length: "2.20 meter",
    lengthMeter: 2.2,
    price: 12500,
    priceBulk: 9500,
    minBulkQty: 50,
    rating: 4.9,
    sold: 4100,
    isPopular: true,
    isBestSeller: true,
    image: "assets/images/wall-moulding.jpg",
    description: "List profil ramping khusus dekorasi dinding (wall moulding frame/pigura). Mempercantik backdrop TV, dinding headboard tempat tidur, dan lorong rumah dengan aksen mewah ala interior Pinterest.",
    specs: [
      { label: "Bahan", value: "Gypsum Roving Padat Presisi Halus" },
      { label: "Panjang Efektif", value: "2.20 Meter / Batang" },
      { label: "Lebar Muka", value: "4 cm" },
      { label: "Ketebalan", value: "10 mm" },
      { label: "Pemasangan", value: "Lem Sealant / Kompon Perekat" }
    ]
  },
  {
    id: "gp-09",
    code: "GP-402",
    name: "List Wall Moulding Pigura Dinding 6cm",
    category: "wall-moulding",
    categoryLabel: "Wall Moulding Dinding",
    width: "6 cm",
    widthNumber: 6,
    length: "2.20 meter",
    lengthMeter: 2.2,
    price: 15500,
    priceBulk: 12500,
    minBulkQty: 50,
    rating: 4.9,
    sold: 2800,
    isPopular: true,
    isBestSeller: false,
    image: "assets/images/wall-moulding.jpg",
    description: "Profil bingkai dinding ukuran medium dengan kurva ganda yang lembut. Memberikan kedalaman visual elegan pada dinding cat polos.",
    specs: [
      { label: "Bahan", value: "Gypsum Casting Roving High Grade" },
      { label: "Panjang Efektif", value: "2.20 Meter / Batang" },
      { label: "Lebar Muka", value: "6 cm" },
      { label: "Ketebalan", value: "12 mm" }
    ]
  },
  {
    id: "gp-10",
    code: "GP-501",
    name: "Ornamen Plafon Ceiling Rose Motif Bunga 60cm",
    category: "ornamen",
    categoryLabel: "Ornamen & Center Panel",
    width: "Diameter 60 cm",
    widthNumber: 60,
    length: "1 Pcs",
    lengthMeter: 0.6,
    price: 85000,
    priceBulk: 70000,
    minBulkQty: 10,
    rating: 5.0,
    sold: 670,
    isPopular: true,
    isBestSeller: true,
    image: "assets/images/ornamen-center.jpg",
    description: "Ornamen tengah plafon bundar (medallion/ceiling rose) untuk dudukan lampu gantung atau kipas angin plafon. Motif relief kembang artistik cetakan super detail.",
    specs: [
      { label: "Bahan", value: "Casting Gypsum Tebal + Rangka Serat Anyaman" },
      { label: "Diameter Luar", value: "60 cm" },
      { label: "Diameter Lubang Kabel", value: "3 - 5 cm (Bisa disesuaikan)" },
      { label: "Ketebalan Relief", value: "25 - 35 mm" }
    ]
  },
  {
    id: "gp-11",
    code: "GP-502",
    name: "Ornamen Plafon Center Panel Klasik 80cm",
    category: "ornamen",
    categoryLabel: "Ornamen & Center Panel",
    width: "Diameter 80 cm",
    widthNumber: 80,
    length: "1 Pcs",
    lengthMeter: 0.8,
    price: 135000,
    priceBulk: 115000,
    minBulkQty: 5,
    rating: 4.9,
    sold: 380,
    isPopular: false,
    isBestSeller: false,
    image: "assets/images/ornamen-center.jpg",
    description: "Center panel jumbo untuk ruang utama dan chandelier besar. Memberi daya tarik visual pusat ruangan yang megah dan berkelas.",
    specs: [
      { label: "Bahan", value: "Gypsum Casting Padat + Multi-layer Roving" },
      { label: "Diameter", value: "80 cm" },
      { label: "Finishing", value: "Halus Siap Cat / Efek Gold Leafing" }
    ]
  },
  {
    id: "gp-12",
    code: "GP-601",
    name: "Tepung Kompon Perekat Gypsum Adhesive 20kg",
    category: "aksesoris",
    categoryLabel: "Aksesoris & Bahan Pasang",
    width: "Zak 20 Kg",
    widthNumber: 0,
    length: "Sak",
    lengthMeter: 1,
    price: 75000,
    priceBulk: 68000,
    minBulkQty: 10,
    rating: 4.9,
    sold: 5200,
    isPopular: true,
    isBestSeller: true,
    image: "assets/images/aksesoris.jpg",
    description: "Bubuk lem kompon perekat khusus list profil & compound sambungan gypsum board. Daya rekat super kuat, cepat kering (setting time 15-20 menit), tidak mudah retak rambut.",
    specs: [
      { label: "Kemasan", value: "Sak Kertas Kraft 20 Kg" },
      { label: "Daya Rekat", value: "Ekstra Kuat (Adhesive Bond Max)" },
      { label: "Daya Sebar", value: "± 35 - 45 Batang List Profil per Sak" },
      { label: "Setting Time", value: "15 - 25 Menit" }
    ]
  },
  {
    id: "gp-13",
    code: "GP-602",
    name: "Kasa Lakban Serat Fiber Roving Mesh Roll 50m",
    category: "aksesoris",
    categoryLabel: "Aksesoris & Bahan Pasang",
    width: "Lebar 5 cm",
    widthNumber: 0,
    length: "Roll 50 Meter",
    lengthMeter: 50,
    price: 28000,
    priceBulk: 23000,
    minBulkQty: 20,
    rating: 4.8,
    sold: 3800,
    isPopular: false,
    isBestSeller: false,
    image: "assets/images/aksesoris.jpg",
    description: "Pita serat jaring fiber berperekat (fiber mesh tape) untuk penguat sambungan list gypsum, pertemuan plafon dan dinding agar tahan getaran dan anti retak.",
    specs: [
      { label: "Dimensi", value: "Lebar 50 mm x Panjang 50 Meter" },
      { label: "Bahan", value: "Fiberglass Mesh Self-Adhesive" },
      { label: "Fungsi", value: "Mencegah Retak Sambungan List & Plafon" }
    ]
  }
];

// Nomor WhatsApp tujuan order (dapat disesuaikan)
const WHATSAPP_CONFIG = {
  phone: "6287775600462", // Nomor WhatsApp aktif Harsha Gypsum
  storeName: "Harsha Gypsum",
  location: "Jl. Raya Industri Gypsum No. 88, Cibubur - Jakarta Timur",
  shippingAreas: "Jabodetabek, Karawang, Banten & Ekspedisi Seluruh Indonesia",
  workingHours: "Senin - Sabtu: 08.00 - 17.00 WIB"
};
